services:
  - type: web
    name: arboviroses-backend-final # Este nome é CRÍTICO!
    env: python
    pythonVersion: 3.12.4 # Ou 3.12
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app" # Verifique se está correto para o seu app
