services:
  - type: web
    name: arboviroses-backend-final # Mantenha este nome EXATO
    env: python
    pythonVersion: 3.12.4 # Mantenha a versão do Python correta
    buildCommand: "pip install -r requirements.txt" # Mantenha este comando de build
    startCommand: "gunicorn src.main:app" # <--- MUDE PARA ESTE COMANDO
