services:
  - type: web
    name: seu-servico-aqui
    env: python
    pythonVersion: 3.12.4 # <-- AQUI ALTERA
    buildCommand: "pip install -r requirements.txt"
    startCommand: "application.py" 
  
