services:
  - type: web
    name: arboviroses-backend
    env: python
    plan: free # 
    buildCommand: "pip install -r requirements.txt"
        startCommand: "application.py" 

      - key: PYTHON_VERSION
        value: 3.11.9 # Ou outra versão compatível como 3.12.x

  
